cd "C:\Users\sil\Documents\GitHub\altislife\tool"
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_aircraft.pbo
::DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_armour.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_attach.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_backblast.pbo
::DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_ballistics.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_captives.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_core.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_difficulties.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_fastroping.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_firecontrolsystem.pbo
::DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_gforces.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_goggles.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_grenades.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_hearing.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_interaction.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_inventory.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_magazineRepack.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_map.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_markers.pbo
::DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_medical.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_movement.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_nightVision.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_noRadio.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_overheating.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_parachute.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_ragdolls.pbo
::DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_recoil.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_reload.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_resting.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_safemode.pbo
::DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_smallarms.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_scopes.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_thermals.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_topdownattack.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_vector.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_vehicles.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_weaponSelect.pbo
DSSignFile.exe havena4.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@agm951\addons\agm_wind.pbo

PAUSE