cd "C:\Users\sil\Documents\GitHub\altislife\tool"
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_advanced_ballistics.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_aircraft.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_apl.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_attach.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_backpacks.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_ballistics.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_captives.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_common.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_difficulties.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_disarming.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_dragging.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_explosives.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_flashsuppressors.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_frag.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_goggles.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_grenades.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_hearing.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_hitreactions.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_interact_menu.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_interaction.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_interaction.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_inventory.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_kestrel4500.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_laser.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_laser_selfdesignate.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_laserpointer.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_logistics_uavbattery.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_logistics_wirecutter.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_magazinerepack.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_main.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_map.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_maptools.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_markers.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_microdagr.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_missionmodules.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_modules.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_movement.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_nightvision.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_noidle.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_noradio.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_norearm.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_optics.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_optionsmenu.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_overheating.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_overpressure.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_parachute.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_protection.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_ragdolls.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_recoil.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_reload.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_reloadlaunchers.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_safemode.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_scopes.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_smallarms.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_thermals.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_vector.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_vehicles.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_viewdistance.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_weaponselect.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_weather.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_winddeflection.pbo
DSSignFile.exe havena.biprivatekey C:\Users\sil\Documents\GitHub\altislife\@ace_bis\addons\ace_zeus.pbo

PAUSE